#pragma once

enum
{
    ID_COPY_SELECTED_FILENAME = 1,
    ID_COPY_SELECTED_CRC32,
    ID_COPY_SELECTED_MD5,
    ID_COPY_SELECTED_FILENAME_MD5,
    ID_COPY_SELECTED_FILE_INFO,
    ID_COPY_ALL_ITEM_INFO,
    ID_CLEAR_ALL_ITEM,
    ID_COPY_FILE_PATH,
    ID_COPY_CRC32,
    ID_COPY_MD5,
    ID_COPY_FILE_PATH_MD5,
    ID_COPY_FILE_PATH_CRC32_MD5,
    ID_COPY_ALL,
    ID_EXIT_THIS_APP,
};